import os
import re

def generate_reference_links():
    # Get absolute path relative to this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    
    paper_path = os.path.join(project_root, "paper", "draft_jp.md")
    output_path = os.path.join(project_root, "docs", "notebooklm_source_links.md")
    
    if not os.path.exists(paper_path):
        print(f"Error: Paper not found at {paper_path}")
        return

    with open(paper_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Referencesセクションを探す
    ref_section = re.search(r"## References.*", content, re.DOTALL)
    if not ref_section:
        print("Error: References section not found in the paper.")
        return

    refs = ref_section.group(0).split("\n")[1:] # ヘッダーを除外
    
    links = []
    # 論文内の参考文献からURLやタイトルを抽出（簡易的なマッチング）
    for ref in refs:
        if not ref.strip(): continue
        
        # タイトルと思われる部分を抽出 (ダブルクォーテーション内)
        title_match = re.search(r'"([^"]+)"', ref)
        title = title_match.group(1) if title_match else ref[:50] + "..."
        
        # Google Scholarへの検索リンクを生成（NotebookLMに読み込ませる際のヒントとして）
        search_query = title.replace(" ", "+")
        scholar_link = f"https://scholar.google.com/scholar?q={search_query}"
        
        links.append(f"- **{title}**\n  - Search Link: {scholar_link}\n  - Raw Citation: {ref.strip()}")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# NotebookLM Grounding Source List\n\n")
        f.write("以下のリストは、論文「C-SMC」で使用された参考文献をNotebookLMに読み込ませるためのガイドです。\n")
        f.write("NotebookLMの「ソースを追加」→「ウェブサイト」にて、以下の各文献のPDF直リンクや公開URLを入力してください。\n\n")
        f.write("## 引用文献リスト\n\n")
        f.write("\n".join(links))
        f.write("\n\n---\n*Generated by Antigravity for ResearchProject_Trial1*")

    print(f"Success: Source list generated at {output_path}")

if __name__ == "__main__":
    generate_reference_links()
